# Generated by Django 4.0.6 on 2022-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_caregory_title_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
        migrations.AddField(
            model_name='product',
            name='poster1',
            field=models.ImageField(blank=True, upload_to='products/poster1'),
        ),
        migrations.AddField(
            model_name='product',
            name='poster2',
            field=models.ImageField(blank=True, upload_to='products/poster2'),
        ),
        migrations.AddField(
            model_name='product',
            name='poster3',
            field=models.ImageField(blank=True, upload_to='products/poster3'),
        ),
    ]
