# Generated by Django 4.0.6 on 2022-07-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('grade', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to='review')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
