# Generated by Django 4.0.6 on 2022-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_partner_place_review_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(max_length=100),
        ),
    ]
