# Generated by Django 4.0.6 on 2022-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
