# Generated by Django 4.0.6 on 2022-07-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_review_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='place',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
