# Generated by Django 4.0.6 on 2022-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_partner_options_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
