# Generated by Django 4.0.6 on 2022-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_amount_alter_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
