# Generated by Django 4.0.6 on 2022-07-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unitfmeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=100)),
                ('sh', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'единица измерение',
                'verbose_name_plural': 'единица измерение',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.caregory', verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='window')),
                ('category', models.ManyToManyField(blank=True, null=True, to='shop.caregory', verbose_name='категория')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.unitfmeasurement', verbose_name='единица измерение')),
                ('product', models.ManyToManyField(blank=True, null=True, to='shop.product', verbose_name='продукция')),
            ],
        ),
    ]
