# Generated by Django 4.0.6 on 2022-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_unitfmeasurement_sh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'verbose_name': 'Готовые окна', 'verbose_name_plural': 'Готовые окна'},
        ),
        migrations.RemoveField(
            model_name='unitfmeasurement',
            name='p',
        ),
        migrations.AddField(
            model_name='unitfmeasurement',
            name='measurements',
            field=models.CharField(default='', max_length=100, verbose_name='единица измерение'),
        ),
        migrations.AddField(
            model_name='window',
            name='choice',
            field=models.BooleanField(default=True, verbose_name='25см оставить'),
        ),
        migrations.AddField(
            model_name='window',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='window',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=100),
        ),
        migrations.AddField(
            model_name='window',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='window',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.caregory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='window',
            name='product',
            field=models.ManyToManyField(blank=True, to='shop.product', verbose_name='продукция'),
        ),
    ]
