# Generated by Django 4.0.6 on 2022-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_window_choice_alter_window_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unitfmeasurement',
        ),
        migrations.AlterField(
            model_name='caregory',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='window',
            name='choice',
            field=models.CharField(choices=[('tr', 'Да'), ('fa', 'Нет')], default='tr', max_length=2, verbose_name='25см оставить'),
        ),
        migrations.AlterField(
            model_name='window',
            name='measurement',
            field=models.CharField(choices=[('PM', 'П.М'), ('ST', 'ШТ')], default='PM', max_length=2, verbose_name='единица измерения'),
        ),
    ]
