# Generated by Django 4.0.6 on 2022-07-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='window',
            name='count',
        ),
        migrations.RemoveField(
            model_name='window',
            name='price',
        ),
        migrations.RemoveField(
            model_name='window',
            name='total',
        ),
    ]
