# Generated by Django 4.0.6 on 2022-07-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_product_measurement_remove_window_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='category',
        ),
        migrations.RemoveField(
            model_name='window',
            name='product',
        ),
        migrations.AddField(
            model_name='window',
            name='product',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукция'),
        ),
    ]
