# Generated by Django 4.0.6 on 2022-07-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_window_count_window_count_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='count_detail',
            field=models.IntegerField(blank=True, default=0, verbose_name='Каличество для деталя'),
        ),
        migrations.AlterField(
            model_name='window',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='window'),
        ),
        migrations.AlterField(
            model_name='window',
            name='price_detail',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, verbose_name='цена для деталя'),
        ),
        migrations.AlterField(
            model_name='window',
            name='product_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='shop.product', verbose_name='продукция для деталя'),
        ),
    ]
