# Generated by Django 4.0.6 on 2022-07-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_window_count_detail_alter_window_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='choice_down',
            field=models.CharField(choices=[('tr', 'Да'), ('fa', 'Нет')], default='tr', max_length=2, verbose_name='25см оставить'),
        ),
        migrations.AddField(
            model_name='window',
            name='count_detail_down',
            field=models.IntegerField(blank=True, default=0, verbose_name='Каличество для деталя'),
        ),
        migrations.AddField(
            model_name='window',
            name='count_down',
            field=models.IntegerField(default=0, verbose_name='Каличество'),
        ),
        migrations.AddField(
            model_name='window',
            name='measurement_detail_down',
            field=models.CharField(choices=[('PM', 'П.М'), ('ST', 'ШТ')], default='PM', max_length=2, verbose_name='единица измерения для деталя'),
        ),
        migrations.AddField(
            model_name='window',
            name='measurement_down',
            field=models.CharField(choices=[('PM', 'П.М'), ('ST', 'ШТ')], default='PM', max_length=2, verbose_name='единица измерения'),
        ),
        migrations.AddField(
            model_name='window',
            name='price_detail_down',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, verbose_name='цена для деталя'),
        ),
        migrations.AddField(
            model_name='window',
            name='price_down',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='window',
            name='product_detail_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_down', to='shop.product', verbose_name='продукция для деталя'),
        ),
        migrations.AddField(
            model_name='window',
            name='product_down',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_down', to='shop.product', verbose_name='продукция'),
        ),
    ]
