# Generated by Django 4.0.6 on 2022-07-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_window_choice_down_window_count_detail_down_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='window',
            name='choice_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='count',
        ),
        migrations.RemoveField(
            model_name='window',
            name='count_detail',
        ),
        migrations.RemoveField(
            model_name='window',
            name='count_detail_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='count_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='window',
            name='measurement_detail',
        ),
        migrations.RemoveField(
            model_name='window',
            name='measurement_detail_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='measurement_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='price',
        ),
        migrations.RemoveField(
            model_name='window',
            name='price_detail',
        ),
        migrations.RemoveField(
            model_name='window',
            name='price_detail_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='price_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='product',
        ),
        migrations.RemoveField(
            model_name='window',
            name='product_detail',
        ),
        migrations.RemoveField(
            model_name='window',
            name='product_detail_down',
        ),
        migrations.RemoveField(
            model_name='window',
            name='product_down',
        ),
        migrations.AlterField(
            model_name='window',
            name='choice',
            field=models.CharField(choices=[('tr', 'Да'), ('fa', 'Нет')], default='tr', max_length=2, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='window',
            name='image',
            field=models.ImageField(blank=True, db_index=True, upload_to='window', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='WindowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('PM', 'П.М'), ('ST', 'ШТ')], default='PM', max_length=2, verbose_name='единица измерения')),
                ('count', models.IntegerField(default=0, verbose_name='Каличество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.window')),
                ('product', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукция')),
            ],
        ),
    ]
