# Generated by Django 4.0.6 on 2022-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_window_choice_down_remove_window_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='choice',
            field=models.CharField(choices=[('tr', 'Да'), ('fa', 'Нет')], default='tr', max_length=2, verbose_name='25 cm оставить'),
        ),
        migrations.RemoveField(
            model_name='windowmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='windowmodel',
            name='product',
            field=models.ManyToManyField(blank=True, default=True, null=True, to='shop.product', verbose_name='продукция'),
        ),
    ]
