# Generated by Django 4.0.6 on 2022-07-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_window_choice_remove_windowmodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowmodel',
            name='product',
        ),
        migrations.AddField(
            model_name='windowmodel',
            name='product',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукция'),
        ),
    ]
