# Generated by Django 4.0.6 on 2022-07-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_windowmodel_product_windowmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.window'),
        ),
    ]
