# Generated by Django 4.0.6 on 2022-07-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_windowmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('image', models.ImageField(blank=True, db_index=True, upload_to='pedestal', verbose_name='Фото')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.caregory')),
            ],
            options={
                'verbose_name': 'Палястра',
                'verbose_name_plural': 'Палястры',
            },
        ),
        migrations.AddField(
            model_name='window',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.caregory', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='window',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Названия'),
        ),
        migrations.CreateModel(
            name='PedestalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, db_index=True, upload_to='pedestal/model', verbose_name='Размер')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('measurement', models.CharField(choices=[('PM', 'П.М'), ('ST', 'ШТ')], default='PM', max_length=2, verbose_name='единица измерения')),
                ('count', models.IntegerField(default=0, verbose_name='Каличество')),
                ('size_1', models.IntegerField(verbose_name='размер')),
                ('size_2', models.IntegerField(verbose_name='размер')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.pedestal')),
            ],
        ),
    ]
