# Generated by Django 4.0.6 on 2022-07-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_pedestal_window_category_window_title_pedestalmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedestal',
            options={'ordering': ('id',), 'verbose_name': 'Палястра', 'verbose_name_plural': 'Палястры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ('id',), 'verbose_name': 'Готовые окна', 'verbose_name_plural': 'Готовые окна'},
        ),
        migrations.AlterModelOptions(
            name='windowmodel',
            options={'verbose_name': 'Экземпляр', 'verbose_name_plural': 'Экзепляры'},
        ),
        migrations.RemoveField(
            model_name='windowmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='windowmodel',
            name='category_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='window', to='shop.window'),
        ),
        migrations.AlterField(
            model_name='window',
            name='choice',
            field=models.CharField(choices=[('dt', 'Верх и внизу оставить'), ('fa', 'Нет'), ('top', 'Верхний части оставить'), ('down', 'Нижний части оставить')], default='dt', max_length=4, verbose_name='25 cm оставить'),
        ),
        migrations.AlterField(
            model_name='window',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Названия'),
        ),
    ]
