# Generated by Django 4.0.6 on 2022-07-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_pedestal_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windowmodel',
            old_name='category_1',
            new_name='category',
        ),
        migrations.AddField(
            model_name='pedestalmodel',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Если два размера'),
        ),
        migrations.AddField(
            model_name='pedestalmodel',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='pedestalmodel',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='windowmodel',
            name='choice',
            field=models.CharField(choices=[('dn', 'нижний част'), ('wh', 'верхний част'), ('dw', 'верхний и нижный част'), ('bk', 'бокавые части'), ('dl', 'деталь')], default='dn', max_length=5, verbose_name='Част'),
        ),
        migrations.AlterField(
            model_name='pedestalmodel',
            name='size_2',
            field=models.IntegerField(null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='windowmodel',
            name='product',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукция'),
        ),
    ]
