# Generated by Django 4.0.6 on 2022-07-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_pedestalmodel_options_remove_window_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.window')),
            ],
        ),
        migrations.RemoveField(
            model_name='windowmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='windowmodel',
            name='category',
            field=models.ManyToManyField(related_name='window', through='shop.Window_Model', to='shop.window'),
        ),
        migrations.AddField(
            model_name='window_model',
            name='window_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.windowmodel'),
        ),
    ]
