# Generated by Django 4.0.6 on 2022-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_remove_windowmodel_category_windowmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowmodel',
            name='choice',
            field=models.CharField(choices=[('dn', 'нижний часть'), ('wh', 'верхний часть'), ('dw', 'верхний и нижный часть'), ('bk', 'бокавые части'), ('dl', 'деталь')], default='dn', max_length=5, verbose_name='Част'),
        ),
        migrations.AlterField(
            model_name='windowmodel',
            name='choice_window',
            field=models.CharField(choices=[('true', 'Да'), ('false', 'Нет')], default='false', max_length=5, verbose_name='25 cm оставить'),
        ),
    ]
