# Generated by Django 4.0.6 on 2022-07-27 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_windowmodel_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedestal',
            options={'ordering': ('id',), 'verbose_name': 'Стойка', 'verbose_name_plural': 'Стойка'},
        ),
        migrations.AddField(
            model_name='pedestal',
            name='available',
            field=models.BooleanField(default=True, verbose_name='наличие'),
        ),
        migrations.AddField(
            model_name='pedestal',
            name='descriptions',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='window',
            name='available',
            field=models.BooleanField(default=True, verbose_name='наличие'),
        ),
        migrations.AddField(
            model_name='window',
            name='descriptions',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pedestalmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack', to='shop.pedestal'),
        ),
        migrations.AlterField(
            model_name='pedestalmodel',
            name='size_2',
            field=models.IntegerField(default=0, null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='window',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.caregory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='windowmodel',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='продукция'),
        ),
    ]
