# Generated by Django 4.0.6 on 2022-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_pedestal_options_pedestal_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedestal',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
