# Generated by Django 4.0.6 on 2022-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_rename_name_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedestalmodel',
            name='count',
        ),
        migrations.AddField(
            model_name='pedestalmodel',
            name='choice',
            field=models.CharField(choices=[('angular', 'угловой'), ('facial', 'лицовой')], default='angular', max_length=10, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='pedestalmodel',
            name='choice_1',
            field=models.CharField(choices=[('top', 'Верхний часть'), ('average', 'Средний часть'), ('lower', 'Нижний часть')], default='top', max_length=10, verbose_name='часть'),
        ),
        migrations.AlterField(
            model_name='pedestalmodel',
            name='measurement',
            field=models.CharField(choices=[('PM', 'П.М'), ('SHT', 'ШТ')], default='PM', max_length=10, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='windowmodel',
            name='choice',
            field=models.CharField(choices=[('dn', 'нижний часть'), ('wh', 'верхний часть'), ('dw', 'верхний и нижный часть'), ('bk', 'бокавые части'), ('dl', 'деталь')], default='dn', max_length=5, verbose_name='Часть'),
        ),
    ]
