# Generated by Django 4.0.6 on 2022-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_remove_pedestalmodel_measurement2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedestalmodel',
            old_name='size_2',
            new_name='size_3',
        ),
        migrations.AddField(
            model_name='pedestalmodel',
            name='price_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='pedestalmodel',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='цена'),
        ),
    ]
