# Generated by Django 4.0.6 on 2022-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_rename_size_2_pedestalmodel_size_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedestalmodel',
            name='price_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, null=True, verbose_name='цена'),
        ),
    ]
