# Generated by Django 4.0.6 on 2022-07-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_pedestalmodel_price_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedestalmodel',
            name='price_4',
        ),
    ]
