# Generated by Django 4.0.6 on 2022-08-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_rename_size_3_pedestalmodel_size_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windowmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='windowmodel',
            name='count',
            field=models.IntegerField(default=0, null=True, verbose_name='каличество'),
        ),
    ]
