# Generated by Django 4.0.6 on 2022-07-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pharetra', models.IntegerField()),
                ('uorttitor', models.IntegerField()),
                ('quisque', models.CharField(max_length=150)),
                ('aliquet', models.IntegerField()),
                ('poster', models.ImageField(blank=True, upload_to='ProductPortfolio')),
                ('image1', models.ImageField(blank=True, upload_to='ProductPortfolio/image1')),
                ('image2', models.ImageField(blank=True, upload_to='ProductPortfolio/image2')),
                ('image3', models.ImageField(blank=True, upload_to='ProductPortfolio/image3')),
                ('discriptions', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар портфолии',
                'verbose_name_plural': 'Товары портфолии',
            },
        ),
    ]
